# Generated by Django 3.2.8 on 2021-11-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=30, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_signup', models.DateTimeField(auto_now_add=True, verbose_name='date signup')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': '유저 정보',
            },
        ),
        migrations.CreateModel(
            name='Congestion_points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_time', models.DateTimeField()),
                ('value', models.FloatField(max_length=5)),
                ('people', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': '혼잡도 테이블',
                'ordering': ['input_time'],
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q_text', models.TextField()),
                ('A_text', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'FAQ 목록',
            },
        ),
        migrations.CreateModel(
            name='turnover_points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_time', models.DateTimeField()),
                ('table_id', models.SmallIntegerField()),
                ('table_pnum', models.SmallIntegerField()),
            ],
            options={
                'verbose_name_plural': '순환율 테이블',
                'ordering': ['input_time'],
            },
        ),
    ]
