# Generated by Django 3.2.8 on 2021-11-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuzzbuzz_app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Congestion_points_SH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_time', models.DateTimeField()),
                ('value', models.FloatField(max_length=5)),
                ('people', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': '혼잡도 테이블 / SH',
                'ordering': ['input_time'],
            },
        ),
        migrations.CreateModel(
            name='turnover_points_SH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_time', models.DateTimeField()),
                ('total_turn', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': '순환율 테이블 / SH',
                'ordering': ['input_time'],
            },
        ),
        migrations.CreateModel(
            name='turnover_temp_HJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_time', models.DateTimeField()),
                ('table_id', models.SmallIntegerField()),
                ('table_pnum', models.SmallIntegerField()),
            ],
            options={
                'ordering': ['input_time'],
            },
        ),
        migrations.RenameModel(
            old_name='Congestion_points',
            new_name='Congestion_points_HJ',
        ),
        migrations.RenameModel(
            old_name='turnover_points',
            new_name='turnover_points_HJ',
        ),
        migrations.AlterModelOptions(
            name='congestion_points_hj',
            options={'ordering': ['input_time'], 'verbose_name_plural': '혼잡도 테이블 / HJ'},
        ),
        migrations.AlterModelOptions(
            name='turnover_points_hj',
            options={'ordering': ['input_time'], 'verbose_name_plural': '순환율 테이블 / HJ'},
        ),
    ]
